### ISSUE TITLE
Version 0.0.2 is missing from Maven Central

### ISSUE THREAD

**Issue by ghataa** [ryansgot/android-java-coverage-merger#11]
I saw that you already moved version 0.1.0 to Maven Central. Could you also move version 0.0.2, please?

**Comment by ryansgot** [comment]
Sure. I've submitted what I believe to be version 0.0.2 to mavenCentral, having looked at the commit history (unfortunately this release did not have a tag associated with it). Please give it a couple hours to show up.

**Comment by ryansgot** [comment]
I'm also curious why you want to use version 0.0.2. In any case, the code for 0.0.2 is here: https://github.com/ryansgot/android-java-coverage-merger/tree/ryan/rerelease_0-0-2

**Comment by ryansgot** [comment]
I just checked. Maven central search and it's at least available: https://search.maven.org/artifact/com.fsryan.gradle.coverage/android-java-coverage-merger/0.0.2/jar

Let me know if it works/does not work for you.

**Comment by ghataa** [comment]
Thanks @ryansgot for the fast reaction! Now it works fine.

I needed it because it broke one of my current pipeline. On one hand, upgrading to 0.1.0 would require further modifications because of the higher gradle version, on the other hand, 0.0.2 worked just fine so it was the easiest solution.

**Comment by ryansgot** [comment]
@ghataa That's understandable. I'm happy that everything is working well for you. Let me know if there is anything else I can do to help.
